### ISSUE TITLE
Fullscreen in FF differs from fullscreen in Chrome (Dashboard 1.11.0)

### ISSUE THREAD

**Issue by ochm** [StefanCohen/OctoPrint-Dashboard#100]
If i do click on Fullscreen (Esc to cancel) icon,  in Chrome is displayed Dashboard in fullscreen, pretty nice. Closed can be with Esc or click on the same icon (link). Perfect behavior.

In Firefox ESR, in normal screen if the Fullscreen icon is clicked, the browser displays the same window, but in Fullscreen, very similar as the F11 is pressed. And if i do click on the same icon again, the real fullscreen of Dashboard is displayed (like in Chrome after first click).
Click again on icon in fullscreen does nothing, fullscreen can be closed only by Esc key.

**Expected behavior**
IMHO in Firefox should be the same behavior like in Chrome

- RPi 4
- OctoPrint version : 1.3.11
- OctoPi version    : 0.17.0
- OS and version: W8.1 64bit CZ
- Browser and version Chrome  77.0.3865.120, 64bit CZ, FF 60.9.0esr 32bit CZ

Thank You.

**Comment by StefanCohen** [comment]
I haven't tested with FF ESR, only the latest Rapid Release. I have just published a new release (1.11.1) with a bug fix to address issue #96. Please try it in ESR to see if it works as expeced now. You may have to clear caches for it to work.
