### ISSUE TITLE
Estimated total print time is empty if PrintTimeGenius is not running

### ISSUE THREAD

**Issue by mdaneman** [StefanCohen/OctoPrint-Dashboard#101]
I know that this is a bit long but please take your time and fill in the following information as clearly and detailed as possible. It will shorten the time needed to understand and fix the issue significantly. Please also state versions clearly when applicable. "Latest version" doesn't help much.  

**Describe the bug**
When PrintTimeGenius plugin is not installed/disabled, the "Estimated total print time" value (after the "question mark") is always empty.

**To Reproduce**
Run Dashboard without PrintTimeGenius

**Expected behavior**
Expected the estimated print time shown in the "Approx total print time" box  on the left of Octoprint to be shown here.

**OctoPrint server and Plugins:**
 - Platform: Rpi 3B
 - OS and version: Raspbian Stretch,
 - OctoPrint version: 1.3.11
 - OctoPi version: 
 - Dashboard version 1.11.0
 - DisplayLayerProgress version 1.14.0

**Desktop (please complete the following information):**
 - OS and version: Windows 10
 - Browser and version Chrome/Safari/any browser

**Comment by StefanCohen** [comment]
Thanks for the feedback. I haven't been able to reproduce this at all. I only have PrintTimeGenius installed on one (my "production" machine) out of four OctoPrint servers and none of them shows the problem you describe. 

Here's one job running on my primary dev machine- 1.3.11 (RPi 3b) with Dashboard 1.11.0 and PrintTimeGenius is not installed:

![Screenshot 2019-10-22 at 08 28 24](https://user-images.githubusercontent.com/33824565/67262771-36a45a80-f4a6-11e9-8256-b858b549ff88.png)

Here it is with "Show fuzzy time estimates" turned off:

![Screenshot 2019-10-22 at 08 32 09](https://user-images.githubusercontent.com/33824565/67262870-93077a00-f4a6-11e9-8aef-93b802314507.png)

Do you see any errors in your browser console?

**Comment by mdaneman** [comment]
Here's a screenshot showing the issue.  It's possible that the problem is that PrintTimeGenius is actually installed, but the plugin is disabled.  I'll try uninstalling PTG completely and see if it fixes it.

![DashboardBug1](https://user-images.githubusercontent.com/35081544/67298685-7405e980-f4a0-11e9-91c2-d85469cceed5.png)

**Comment by StefanCohen** [comment]
I have tried with just disabling the plugin but It still works for me. What does the "Approx. Total Print Time" in the sidebar say when the Dashboard prints "-". 

The thing is that the Dashboard is totally independent from PrintTimeGenius. It gets the value directly from Octoprint so I have a hard time to imagine what could cause this bug.

**Comment by mdaneman** [comment]
Come to think of it, it's not showing the estimated print time on left side either.  I have the "M73 ETA Override" plugin running.  I wonder it that's what's doing it.  I'll play around with disabling it and see if that makes a difference.
![Annotation 2019-10-22 183529](https://user-images.githubusercontent.com/35081544/67348907-397d6a80-f4fb-11e9-97f3-74c25dcab7c3.jpg)

**Comment by StefanCohen** [comment]
That is the problem. There is no value for me to display on the Dashboard.
