### ISSUE TITLE
Dashboard and Enclosure Plugin

### ISSUE THREAD

**Issue by VladimirMalinin** [StefanCohen/OctoPrint-Dashboard#102]
Hi! Amazing plugin!

But i have a problem with enclosure plugin. If it on, Dashboard write me, what i need install DisplayLayerPlugin. When Enclosure Plugin is off, i don't see problem.

Mi octopi log here
[octoprint.log](https://github.com/StefanCohen/OctoPrint-Dashboard/files/3757106/octoprint.log)

**Comment by StefanCohen** [comment]
You will need to install DisplayLayerProgress. It is required for the Dashboard to work.

**Comment by VladimirMalinin** [comment]
> You will need to install DisplayLayerProgress. It is required for the Dashboard to work.

Yes, i use DisplayLayerProgress, and it work perfectly with your Dashboard =) The problem begins, if i install Enclosure Plugin. If I turn off this plugin everything works again.

**Comment by VladimirMalinin** [comment]
Maybe some special setup is required for Enclosure Plugin?

**Comment by StefanCohen** [comment]
Ok. That is strange. I have Enclosure running together with the Dashboard on three different RPis. 

I can't see anything suspicious in the logfile except a bunch of errors from your language pack but that is probably unrelated. Do you see any errors in the browser console if you turn enclosure back on?

**Comment by VladimirMalinin** [comment]
No, i'm not see errors.

So, this is my dashboard, enc plugin turn off:
![2019-10-25 09-33-39 MiBot  OctoPrint  - Google Chrome](https://user-images.githubusercontent.com/56886690/67548558-c2b6bc00-f70a-11e9-8b6f-15233773cc63.jpg)

Then
Enclosure turned on, and DisplayLayerProgress has updated on 1.14.1

Restart
Ooooops... As soon i install new update for display layer progress, octoprint crashed and load on safe mode. 

I reinstall all plugins now - dashboard, enclosure, display:
First DisplayLayerProgress (1.14.1) - ok
![2019-10-25 10-23-29 MiBot  OctoPrint  - Google Chrome](https://user-images.githubusercontent.com/56886690/67551430-88045200-f711-11e9-920f-242a3ec8edf2.jpg)
Second Dashboard (1.11.1) - oooops...  
![2019-10-25 10-29-43 MiBot  OctoPrint  - Google Chrome](https://user-images.githubusercontent.com/56886690/67551836-7ff8e200-f712-11e9-91d9-1e77dcc3ca18.jpg)
Newermind, install Enclosure 4.13. Without changes.

It seems that the plugin settings remained after uninstall. It might be worth trying to remove them, but I don’t know where they are located.

I can give you access to my printer if you want =)
If we don’t find a solution, I’ll try to completely reinstall the octoprint, but this is too radical a way to solve the problem =D

**Comment by StefanCohen** [comment]
I have tried to reproduce this multiple times not but I have failed. I will close this for now. Please let me know if it behaves the same on a clean install.

**Comment by VladimirMalinin** [comment]
Hi. I reinstall my octoprint on new sd card. install display layer progress, enclosure plugin, dashboard, and he doesn't work. i don't understand what's hAppend.
[octoprint.log](https://github.com/StefanCohen/OctoPrint-Dashboard/files/3896533/octoprint.log)
