### ISSUE TITLE
Small bug - Fan speed shows 1 percent lower than set

### ISSUE THREAD

**Issue by ochm** [StefanCohen/OctoPrint-Dashboard#104]
Hi Stefan, i found small bug in fan speed.
In slicer is set 50%, in printer settings i see number 127 (can be 0-255), but your Dashboard shows 49%. Can you do small correction, please?

Sincerely
Martin

**Comment by StefanCohen** [comment]
I can reproduce that by setting the speed to 50% in Cura. The fan speed is however not calculated by the Dashboard plugin. It is one of the metrics produced by DisplayLayerProgress and it is simply rendered by the Dashboard:

![Screenshot 2019-10-24 at 09 04 29](https://user-images.githubusercontent.com/33824565/67461343-620d7d80-f63d-11e9-9507-634987a0f588.png)

I suggest that you report this issue to the author of [DisplayLayerProgress](https://github.com/OllisGit/OctoPrint-DisplayLayerProgress/issues) so he can take a look at it.

**Comment by ochm** [comment]
Done https://github.com/OllisGit/OctoPrint-DisplayLayerProgress/issues/91
