### ISSUE TITLE
Problem to load Gcode with DisplayLayerProgress

### ISSUE THREAD

**Issue by Lanzentraeger** [StefanCohen/OctoPrint-Dashboard#112]
The Problem with Dashboard and DisplayLayerProgress is, the Printer stops working when you send the Gcode of a new file to Octoprint.
Why need DisplayLayerProgress, that needs a Layer information output in the Gcode? It takes much more time to slice the File and makes Problems when you send Files while printing.
When i install the Plugin LayerDisplay, there are no problems while Printing to read the Layers and it needs NO Gcode in the Slicer. 
The Problem is, Dashboard only works with Plugin DisplayLayerProgress.
Is it possible to make it work with the LayerDisplay Plugin, that not kills the Printer performance?
This would be very nice.
At least i have to say, i do not know anything about codes, sorry. I am only a user and say thank you for the cool Plugins.
Greetings Chris

**Comment by StefanCohen** [comment]
Thanks for the feedback. No. It is not possible to switch to LayerDisplay as it doesn't provide the data I need. DisplayLayerProgress also provides the API i need to get the required info during the print. DisplayLayerProgress injects the required gcodes during upload to octoprint, not during slicing. Slicing is in fact not affected at all by that plugin.
