### ISSUE TITLE
Missing layer time chart

### ISSUE THREAD

**Issue by ochm** [StefanCohen/OctoPrint-Dashboard#117]
As far as i know, i did only update DisplayLayerProgress Plugin: to 1.16.0,
and from this time the dashboard doesn't show some informations
![dashboard](https://user-images.githubusercontent.com/47606742/71780261-afed1d00-2fc0-11ea-9773-93e2c699787c.PNG)
Should i do downgrade the Display layer progress plugin, or is some chance to repair Dasboard?
Dashboard Plugin: 1.11.1 
Sincerely

**Comment by divisl** [comment]
I have the same problém, thx.

**Comment by ochm** [comment]
Probably bug in Plugin as described in https://github.com/OllisGit/OctoPrint-DisplayLayerProgress/issues/104

**Comment by StefanCohen** [comment]
This is most likely the bug in DisplayLayerProgress as you mentioned as the latest version doesn't provide the layer updates as previous versions did. Closing.
