### ISSUE TITLE
Total/Current layers displays NaN

### ISSUE THREAD

**Issue by skint007** [StefanCohen/OctoPrint-Dashboard#12]
I'm loving the dashboard so far, great work!

I have installed the display layers plug that it relies on but for some reason it doesn't display correctly. I've attached a screenshot. Any ideas?

Thank you :)

![image](https://user-images.githubusercontent.com/37035851/64801241-f95ebb80-d53c-11e9-8a4d-cb15dd116424.png)

**Comment by jimmyeao** [comment]
I also have this problem, AND it breaks the layer display on the left nav (plugin DisplayLayerProgress Plugin)

**Comment by StefanCohen** [comment]
I have refactored the way the Layer info is propagated  in 1.1.0 I have however not been able to reproduce the problem with the data from displaylayerprogress taking so long to propagate to the dashboard. Could this be a conflict with some setting in displaylayerprogress or some other plugin? I suggest that you open a separate issue for that
