### ISSUE TITLE
Time on tab bar 1 hour too early.

### ISSUE THREAD

**Issue by Tillema** [StefanCohen/OctoPrint-Dashboard#121]
When printing, the tab bar in the explorer shows the percentage and the time the print will be ready.
And then the issue: the time is incorrect. The dashboard itself shows the right time, but the time in the bar is exactly 1 hour too early. I see 2 options:
- In Amsterdam we have GMT +1
- In most European countries we have daylight saving time (in summer the time shifts one hour forward).
I don't know if this relates to the dashboard plugin, but since I added this, I saw the tab shows something different.

**Comment by OllisGit** [comment]
Hi @Tillema ,
the Time in the Browser-Tab is provided by the DisplayLayerProgress-Plugin since 1.17.0.

This issue is already reported and will be fixed in the next DLP-Version: 
https://github.com/OllisGit/OctoPrint-DisplayLayerProgress/issues/108
