### ISSUE TITLE
Estimated total print time is empty while printing via API

### ISSUE THREAD

**Issue by ochm** [StefanCohen/OctoPrint-Dashboard#122]
I found problem with Estimated total print time in Dashboard (1.11.1)
The time is displayed only when the gcode is printed from internal storage.
When the print is sent via API (from Prusa Slicer), the Estimated total print time is empty.
Information from author of DisplayLayerPlugin - this item is not driven by his plugin.
https://github.com/OllisGit/OctoPrint-DisplayLayerProgress/issues/109#issuecomment-578530574
Thank you.

**Comment by StefanCohen** [comment]
The estimated total print time is coming straight from OctoPrint via the PrinterStateModel viewmodel and is not manipulated in any way by the Dashboard. Like this:

`printerStateModel.estimatedPrintTimeString()`

I'm regularly printing via the API (from Cura) and haven't seen a problem with this yet. I haven't tried with prusaslicer.

**Comment by ochm** [comment]
So the problem is where?

**Comment by ochm** [comment]
I tried open issue in Octoprint https://github.com/foosel/OctoPrint/issues/3439
