### ISSUE TITLE
Display locale time instead of forcing 24-hour time.

### ISSUE THREAD

**Issue by alsmithson** [StefanCohen/OctoPrint-Dashboard#125]
Hi,
I love Dashboard and I rarely have to visit the other tabs. However, Living in the USA, I don't naturally use 24 hour clocks and I can't just glance at the time values and grasp them. Please use the system locale time and display AM/PM for the various times displayed.

**Comment by StefanCohen** [comment]
I have been waiting for that feedback :) I'll see if I can find a way to address this.

**Comment by StefanCohen** [comment]
Sorry but I haven't found any standard way to do this that wouldn't make the code a complete mess so I'll leave it as ISO 8601 for now.
