### ISSUE TITLE
Hot end temp not displaying

### ISSUE THREAD

**Issue by Sarithz** [StefanCohen/OctoPrint-Dashboard#126]
I'm running into an issue with the hot end gauge no longer working.  Reboots of the server do not help and I have had to uninstall and reinstall the plugin to get it working temporarily again.  It isn't an Octoprint issue as it's stats page does show the temperature correctly.  See the screenshots attached.
![Screen Shot 2020-02-12 at 10 02 01 AM](https://user-images.githubusercontent.com/43412681/74353532-abfea880-4d7f-11ea-9190-af863f18fadb.png)
![Screen Shot 2020-02-12 at 10 02 28 AM](https://user-images.githubusercontent.com/43412681/74353550-b28d2000-4d7f-11ea-95d8-18680c59224a.png)

**Comment by StefanCohen** [comment]
That seems strange. The temps are coming from the same viewmodel as the stats page. I will have to take a look to see if I can replicate the behaviour.

**Comment by Sarithz** [comment]
Your plugin is awesome, and I've no issues at all until about a week ago.  Let me know if anything is needed from my end.

**Comment by StefanCohen** [comment]
Hi again and sorry for the delay. I haven't been able to reproduce this on any of my systems and I haven't received any other reports on this issue. Are you still experiencing problems with this?

**Comment by StefanCohen** [comment]
I'm closing this for now. Please re-open if you still have the issue.
