### ISSUE TITLE
DLP deprecation of "totalHeightWithExtrusion"

### ISSUE THREAD

**Issue by OllisGit** [StefanCohen/OctoPrint-Dashboard#127]
Hi,

I saw in your implementation that you use "totalHeightWithExtrusion", because totalHeight was not available.
https://github.com/StefanCohen/OctoPrint-Dashboard/blob/master/octoprint_dashboard/static/js/dashboard.js#L26

Since Version 1.17.0 the "totalHeight"-attribute is now the correct way to read the height. The calculation is related to the "height mode" in Plugin-Settings.

Please change your plugin to the correct attribute, so that I can remove the other attribute.

Thx, in advance
Olli

**Comment by StefanCohen** [comment]
I finally have had time to set up a new dev env so this will be fixed in the next release.

**Comment by StefanCohen** [comment]
Fixed in 1.11.2
