### ISSUE TITLE
Fan icon has the wrong tool tip

### ISSUE THREAD

**Issue by MattB12** [StefanCohen/OctoPrint-Dashboard#13]
**Describe the bug**
Low priority, this bug does not impact performance at all.
I noticed that the Fan Speed icon has the same tool tip as the Bed Temperature icon when hovering over it.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the dashboard tab.
2. Move the mouse cursor over the Fan Speed icon.
3. Wait.

**Expected behaviour**
I expect the tool tip should say something like "Fan Speed"

**Screenshots**
![image](https://user-images.githubusercontent.com/48497470/64825093-5de24f00-d5ff-11e9-859a-52bf7e5e1eb6.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro v1903
 - Browser: Chrome
 - Version: 76.0.3809.132 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
N/A

**OctoPrint**
 - Version: 1.3.11
 - OS: OctoPi v0.16.0
 - Hardware: Raspberry Pi model 3B

**Additional context**
Fantastic work, I really like your work.

**Comment by StefanCohen** [comment]
Fixed in 1.1.0
