### ISSUE TITLE
LIFT Button

### ISSUE THREAD

**Issue by ifekali** [StefanCohen/OctoPrint-Dashboard#131]
As a Dashboard user, I would love to have a button for lifting the printhead a couple of inches, because whenever I am forced to cancel the print, (and I usually do it from Dashboard tab,) I find myself switching to Control tab to do so. The head usually needs to be lifted in order to resolve the issue on the hotbed.

So I'd like to skip that switching to another tab step.

Thank you for your attention, you are doing great work.

-Izmet Fekali

**Comment by StefanCohen** [comment]
Thanks for the feedback. I'm very reluctant to adding control features to the Dashboard so I will decline this request. Another way to achieve what you want is to add a Gcode Script to lift the head on the "After print job is canceled" event in the OctoPrint settings.
