### ISSUE TITLE
Controls from the Dashboard

### ISSUE THREAD

**Issue by KenLucke** [StefanCohen/OctoPrint-Dashboard#132]
It would be very convenient to be able to click on a progress indicator and bring up a dialog to change that setting.  For instance, click on the Fan progress bar/circle and up pops a dialog to allow you to set the fan speed (%, not just on/off) right from the dashboard, instead of going to the "Control" tab.  Click on the bed temperature indicator, allows you to set the bed temperature instead of going to the "Temperature" tab.  Etc.  This would make it into more of a true "everything on one tab" Dashboard.

**Comment by StefanCohen** [comment]
Please see issues #4 and  #70. I have played with this in the past but never found a solution that I was happy with and the user base is as divided on this feature as I am.
