### ISSUE TITLE
Layer Progress displays 0% or the last value in Chrome

### ISSUE THREAD

**Issue by StarNamer** [StefanCohen/OctoPrint-Dashboard#133]
_Just before I was about to post this, I looked at the similar issues, specifically #8 which indicates that this was originally implemented by "hijacking `gcodeViewModel._processData`" and found a workaround which gets it working, but doesn't indicate what a permanent fix should be._

_Since the GCode file is considered large, opening the GCode Viewer tab displays a warning about loading it into the viewer. This indicates that the GCode Viewer hasn't read the file, so there's no 
 analysis available._ 

_Forcing the viewer to analyse the GCode causes the Layer Gauge on the Dashboard to start working._

**Describe the bug**
On several prints, the Layer progress guage displays 0% throughout the print. On one occasions, it showed 94%, which was the last value left by the previous print and did not get reset.  This may be simillar to issue #110 

**To Reproduce**
At the moment, It's intermittent. I can attach GCode, but am not sure this will reproduce the problem.
_Update: I now think just using a large GCode file should show the behaviour_

**Expected behavior**
Layer progress gauge changes as print of a particular layer progresses.  

**Screenshots**
See attached

**Files (please attach the following Files or screenshots when applicable):**
Zipped log files, screenshot and gcode attached.[Layer progress displays zero percent.zip](https://github.com/StefanCohen/OctoPrint-Dashboard/files/4397069/Layer.progress.displays.zero.percent.zip)

**OctoPrint server and Plugins:**
From the octoprint log:
- INFO - --- Log roll over detected ---------------------------------------------------
- INFO - OctoPrint 1.4.0
- INFO - 22 plugin(s) registered with the system:
|  Action Command Prompt Support (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/action_command_prompt
|  Announcement Plugin (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/announcements
|  Anonymous Usage Tracking (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/tracking
|  Application Keys Plugin (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/appkeys
|  Backup & Restore (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/backup
|  Core Wizard (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/corewizard
|  Dashboard (1.11.4) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_dashboard
|  DisplayLayerProgress Plugin (1.18.1) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_DisplayLayerProgress
|  Error Tracking (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/errortracking
|  Fullscreen Plugin (0.0.4) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_fullscreen
|  Logging (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/logging
|  Login UI (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/loginui
|  Navbar Temperature Plugin (0.13) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_navbartemp
|  Pi Support Plugin (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/pi_support
|  Plugin Manager (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/pluginmanager
|  Preheat Button (0.5.1) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_preheat
|  Printer Safety Check (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/printer_safety_check
|  Resource Monitor (0.2.2) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_resource_monitor
|  Software Update (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/softwareupdate
|  Tab Order (0.5.6) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_taborder
|  Virtual Printer (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/virtual_printer
|  Webcam Tab (0.1.2) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_webcamtab
Prefix legend: ! = disabled, # = blacklisted, * = incompatible
2020-03-28 00:34:38,389 - octoprint.environment - INFO - Detected environment is Python 2.7.16 under Linux (linux2). Details:
|  hardware:
|      cores: 4
|      freq: 1200.0
|      ram: 917008384
|  os:
|      id: linux
|      platform: linux2
|  plugins:
|      pi_support:
|          model: Raspberry Pi 3 Model B Rev 1.2
|          octopi_version: 0.17.0
|  python:
|      pip: 19.3.1
|      version: 2.7.16
|      virtualenv: /home/pi/oprint

**Desktop**
 - OS and version: Windows 10 Pro Insider Preview Build 19592.rs_prerelease_200321-1719
 - Browser and version Google Chrome Version 83.0.4098.0 (Official Build) canary (64-bit)

**Additional context**
I noticed the issue a couple of times with other versions of Chrome and Chrome Canary.

**Comment by StefanCohen** [comment]
Thanks for the feedback. This is as you mentioned related to the GCode viewer in OctoPrint not loading the stl. This can happen if the user disables the GCode viewer in the settings or if the loaded file is too large. There are options in OctoPrint to increase the mem limit for both desktop and mobile clients.
