### ISSUE TITLE
[Feature Request] Python 3 Compatibility

### ISSUE THREAD

**Issue by jneilliii** [StefanCohen/OctoPrint-Dashboard#136]
**Is your feature request related to a problem? Please describe.**
Running the latest version of OctoPrint 1.4.0 in a Python 3 environment plugin is not found in Plugin Manager, because of compatibility flags. I see the plugin is compatible in `__init__.py` but plugin repo has not been updated to list it as compatible.

**Describe the solution you'd like**
Update Plugin Repository with proper compatibility information.

**Additional context**
Please see [here](https://docs.octoprint.org/en/master/plugins/python3_migration.html#telling-octoprint-your-plugin-is-python-3-ready) for the required updates.

**Comment by StefanCohen** [comment]
Thanks for the reminder. Pull request sent to plugin repository.

**Comment by StefanCohen** [comment]
Merged
