### ISSUE TITLE
Job status negative?

### ISSUE THREAD

**Issue by Protoncek** [StefanCohen/OctoPrint-Dashboard#138]
Hello!
My job status is  ... negative...? (see picture). I'm printing face masks from Prusa. 
[https://www.prusaprinters.org/prints/27267-prusa-face-shield-stack-ver/files](url) - I'm printing stack of 8.

No matter, if i load pre-compiled gcode or i compile it myself. When i start to print job status is negative and "print time left" is zero. I have Prusa MK3S printer and in octoprint "M73override" plugin is installed - this plugin shows more accurate "time left", since prusaSlicer calculates this time.

Any clues? Ok, one possibility is the fact that above files are "pumped up" - printer works at spped up to 200% of normal max. speed....?
![dashboard](https://user-images.githubusercontent.com/26406640/78452724-36cb9780-768d-11ea-8204-a21d38d7ae50.jpg)

**Comment by StefanCohen** [comment]
Hi!

The Dashboard simply displays what is reported by OctoPrint. The error seems to be somewhere in the backend and out of my control as the job progress in the sidebar displays the same error. I suggest that you file an issue at the OctoPrint issue tracker.

**Comment by Protoncek** [comment]
Thanks. It seems that the problem is in display layer plugin and the way prusaslicer does layer marking...
