### ISSUE TITLE
Enclosure Plugin Support Not Showing Correct Units When Fahrenheit Selected

### ISSUE THREAD

**Issue by Sarithz** [StefanCohen/OctoPrint-Dashboard#142]
Preface - This is an awesome plugin and I really appreciate the work put into it!

**Describe the bug**
When selecting Fahrenheit instead of Celsius for temperature probe monitors, the Enclosure plugin display the correct unit, but the Dashboard still shows C as the units instead of Fahrenheit.

Screenshots
_Enclosure plugin screenshot_
![image](https://user-images.githubusercontent.com/43412681/79558084-3d80e400-8069-11ea-90d1-8a25e3e117b7.png)

_Dashboard plugin screenshot_
![image](https://user-images.githubusercontent.com/43412681/79558236-7325cd00-8069-11ea-919a-27f01219ccc1.png)

**OctoPrint server and Plugins:**
 - Platform: RPi 3b+
 - OS and version: Raspbian Buster
 - OctoPrint version : 1.4.0
 - OctoPi version    : 0.17.0 - Dashboard version [e.g. Dashboard 1.10.1]

**Comment by StefanCohen** [comment]
Hmm. Yes. The Dashboard is hardcoded for Celcius and ISO 8601 time formats.
