### ISSUE TITLE
Gauge colour change not working.

### ISSUE THREAD

**Issue by mselkin** [StefanCohen/OctoPrint-Dashboard#146]
I know that this is a bit long but please take your time and fill in the following information as clearly and detailed as possible. It will shorten the time needed to understand and fix the issue significantly. Please also state versions clearly when applicable. "Latest version" doesn't help much.  

**Describe the bug**
I am finding that the gauge colour change option only works when the temperature is below the set point (then the gauge is blue and turns green when the set point is reached). However, the gauges never turn red when the temperature is above the set point (at any threshold I tried).

**To Reproduce**
Manually raise hotted temp to 210, then set hotted temp to 200 in octoprint
**Expected behavior**
Gauge should be in red until temp falls to 200 c
**Screenshots**

**Files (please attach the following Files or screenshots when applicable):**
* Octoprint.log
* Browser console log
* gcode file that can be used to reproduce the problem

Any help would be appreciated,

Mark

**Comment by StefanCohen** [comment]
Thanks. I can reproduce this and must have messed up something. I will take a look and try to fix it.

**Comment by StefanCohen** [comment]
Fixed in 1.12.0
