### ISSUE TITLE
Dashboard not properly reading changes in part cooling fan speed

### ISSUE THREAD

**Issue by HaernCalistinson** [StefanCohen/OctoPrint-Dashboard#149]
Version 1.11.14

I sliced a file in Prusa slicer with variable fan speeds. The first 4 layers (the raft) had the part cooling fan off. Then the fan turns on at 30% for several layers. Once the print got to the point that the fan had turned on, and the fan was indeed spinning, the dashboard still displayed it in the off state. 

**Expected behavior**
The dashboard should accurately display the condition of the fan at all times.

**Files (please attach the following Files or screenshots when applicable):**
gcode attached
[puller_nut_12_side_020mmclear_24_20_misterguru_0_2mm_PET_ENDER3_1h47m.txt](https://github.com/StefanCohen/OctoPrint-Dashboard/files/4605125/puller_nut_12_side_020mmclear_24_20_misterguru_0_2mm_PET_ENDER3_1h47m.txt)

**OctoPrint server and Plugins:**
 - Platform: RPi 4b
 - OctoPrint version: 1.4.0
 - OctoPi version: 0.17.0
 - Dashboard version 1.11.14
 
**Desktop (please complete the following information):**
 - OS and version: Win10
 - Browser and version Chrome 81.0.4044.138 (Official Build) (64-bit)

**Comment by StefanCohen** [comment]
Thanks for the feedback. The fan speed value is provided by the DLP Plugin: https://github.com/OllisGit/OctoPrint-DisplayLayerProgress 

I can sort of reproduce your problem as the fanspeed reaches 30% but never 100% during a test print. I noticed that the fan speed indicator flickered between 30 and 100% for a short while after the first few layers but then it settled on 30%. This is most likely an issue in DLP so please post an issue there and include the gcode.
