### ISSUE TITLE
Ability to turn on/off dashboard elements in setup

### ISSUE THREAD

**Issue by mcarlson-sb** [StefanCohen/OctoPrint-Dashboard#15]
**Is your feature request related to a problem? Please describe.**
I currently do not have a fan, therefore I would like to turn off display of the fan speed dashboard element.

**Describe the solution you'd like**
I would like to be able to go into the Dashboard setup and toggle on/off display elements such as the fan speed

**Describe alternatives you've considered**
It might be possible to auto detect that fan input does not exist (this seems be to the case with a second extruder) however, a simple toggle would work well.  it would also allow people with a second extruder that isn't currently in use to be temporarily toggled to off.

**Additional context**

**Comment by StefanCohen** [comment]
Thanks for the suggestion. This will require a setting in the plugin as I don't think OctoPrint provides a "hasFan" method.

**Comment by StefanCohen** [comment]
I have added settings to enable/disable Fan, Octoprint Host System Info and Webcam for now. Chamber and second hotend are enabled/disabled in the OctoPrint Printer Profile settings.

**Comment by StefanCohen** [comment]
Fixed in 1.2.0
