### ISSUE TITLE
Toggle temperature gauges

### ISSUE THREAD

**Issue by Xierion** [StefanCohen/OctoPrint-Dashboard#152]
I am finding the dashboard plugin to be a great addition, however, there is a lot of detail on the page, and the temperature gauges take up a fair majority of screen real estate. The option to toggle the temperature gauges on/off would be great.

**Comment by StefanCohen** [comment]
Thanks for the feedback. I tried to add a setting to hide the hotend(s), chamber and bed temp but found a conflict with the auto-hiding of cold hotends so no dice. Please provide a PR if you want to and I will review it.
