### ISSUE TITLE
support Multicam feeds

### ISSUE THREAD

**Issue by purist69** [StefanCohen/OctoPrint-Dashboard#161]
Would be nice if you could support multiple camera screens on the dashboard via input from the multicam plugin.

**Comment by CynanX** [comment]
I have a pull request up that should do this. Not sure if it'll be accepted but maybe :)

**Comment by CynanX** [comment]
I have a pull request up that should do this. Not sure if it'll be accepted but maybe :)

**Comment by StefanCohen** [comment]
Thanks for the feedback. There are multiple requests for this including #65, #140 and #159 so I will close this as duplicate and refer you to #159 which is still open.
