### ISSUE TITLE
Printer Control

### ISSUE THREAD

**Issue by Klammerson** [StefanCohen/OctoPrint-Dashboard#184]
Using dashboard for a while now I think it would be awesome to have some control elements available like temperature, fan speed and axis movement, maybe next to the displayed items.

I for myself have the widescreen plugin running and the camera and temperature on the left side for monitoring. In the center I have dashboard running but have to switch to temperature or control for minor adjustments during test print or similar.

**Comment by StefanCohen** [comment]
Hi and thanks for the feedback. I have received this feature request multiple times (#4 #70 #132) and decided to not implement it as it is not in scope for the project.

Best regards,
Stefan
