### ISSUE TITLE
Custom Controls

### ISSUE THREAD

**Issue by Pheelix** [StefanCohen/OctoPrint-Dashboard#187]
Any plans to add Custom Controls buttons on the dashboard?  Or even better if you could add the Custom Control Editor plugin buttons to display on dashboard.

Oh and one more request.  The ability to move or change the order it which stuff is listed on dashboard.

Thanks.

**Comment by StefanCohen** [comment]
Hi. I have no plans to add controls to the dashboard. This has been requested many times but I feel that it is out of scope for this plugin. I have been playing with a customizeable dashboard but the progress is slow.  https://community.octoprint.org/t/dashboard-v2-ideas/12717
