### ISSUE TITLE
The webcam URL is broken for some cameras.

### ISSUE THREAD

**Issue by cocotugo** [StefanCohen/OctoPrint-Dashboard#188]
In the following section the date object appended to the returned URL might break some streams   

`self.embedUrl = function () {                     
            if (self.webcamState() > 0 && self.settingsViewModel.settings.webcam && self.settingsViewModel.settings.plugins.dashboard.showWebCam() == true) {
                if(self.MulticamAvailable()) {
                    var urlPosition = self.webcamState() - 1;
                    return self.dashboardMulticamProfiles()[urlPosition].URL() + '?' + new Date().getTime();
                } else {
                    return self.settingsViewModel.settings.webcam.streamUrl() + '?' + new Date().getTime();`

proposed fix (I dont know what is the purpose of returning the date object at the end):
`else { return self.settingsViewModel.settings.webcam.streamUrl();`

**Comment by StefanCohen** [comment]
That added date is to prevent browser caching and is the same mechanism as used by the standard OP webcam stream URL function. Without it, some browsers will display a cached image instead of the stream.
