### ISSUE TITLE
 DisplayLayerprogress plugin link target

### ISSUE THREAD

**Issue by oiv** [StefanCohen/OctoPrint-Dashboard#19]
When  DisplayLayerprogress plugin is not installed there is a link to the plugin. However this link does not have _target=blank which leads the new page to open in same tab as Octoprint is.

So just a minor adjustement wish. Like the other links in normal Octoprin screen. <a href... target="_blank">

**Comment by StefanCohen** [comment]
Makes sense. I’ll fix it.

**Comment by StefanCohen** [comment]
Fixed in 1.1.0
