### ISSUE TITLE
Warning! Can't get stats from DisplayLayerProgress. Is it installed?

### ISSUE THREAD

**Issue by Makhaira** [StefanCohen/OctoPrint-Dashboard#197]
Despite having the relevant plugins installed, Dashboard simply displays the message "Warning! Can't get stats from DisplayLayerProgress. Is it installed?" both during and outside of prints. I have it working successfully on another Octoprint instance

![image](https://user-images.githubusercontent.com/60077178/92111261-fa3ecc00-ede3-11ea-8f0d-56d6289ca3c9.png)
[octoprint.log](https://github.com/StefanCohen/OctoPrint-Dashboard/files/5168270/octoprint.log)

Octoprint Version 1.4.2
Dashboard (1.14.0)
DisplayLayerProgress Plugin (1.23.2)
Multi Line Terminal (0.1.3)
OctoKlipper (0.2.5)
Terminal Commands Extended (0.1.5)
Themeify (1.2.2)

Despite reinstalling both Dashboard and DisplayLayerProgress I cannot get Dashboard to stop displaying this error, which renders the rest of Dashboard largely useless. Any help would be gratefully received.

**Comment by StefanCohen** [comment]
It looks like you may have something else going on that causes a Javascript error. That in turn causes the error message to be displayed even if it has nothing to do with your problem. Please take a look at your JS error console in the browser and report here if you find any errors.

**Comment by Makhaira** [comment]
Thanks I'll check that out tonight.

**Comment by Makhaira** [comment]
![image](https://user-images.githubusercontent.com/60077178/92399556-61c98400-f122-11ea-965a-4092fbe274c7.png)

This is what I find @StefanCohen

**Comment by chilluniverse** [comment]
@Makhaira Did you deactivate the "GCode Viewer" Plugin?

Had the same issue and as you and after I saw this screenshot I realised that I deactivated the GCode Viewer.
So I activated it again and this fixed the problem.

> ![image](https://user-images.githubusercontent.com/60077178/92399556-61c98400-f122-11ea-965a-4092fbe274c7.png)
> 
> This is what I find @StefanCohen

**Comment by Makhaira** [comment]
100% correct! Many thanks. FAQ worthy?

**Comment by StefanCohen** [comment]
Great. It has been in the Help section on the wiki for quite some time: https://github.com/StefanCohen/OctoPrint-Dashboard/wiki/Help#the-dashboard-fails-to-load-with-the-dashboardviewmodel-missing-gcodeviewmodel-error-message

Do you have a suggestion on how to improve it?

**Comment by Makhaira** [comment]
I think the missing info was I never knew to look in the console for that
error message. There's a section somewhere that said you'd get this if
displaylayerprogress wasn't installed, it would maybe be worth linking the
two?

Thanks again for the help.

**Comment by StefanCohen** [comment]
That's a good idea. I'll do it right away. Thanks!
