### ISSUE TITLE
Camera display.

### ISSUE THREAD

**Issue by SargonofAssyria** [StefanCohen/OctoPrint-Dashboard#2]
Nice job! 
On my display there is enough room below the data to display the camera also.
Maybe as a setting to display the camera too on the dashboard.

**Comment by StefanCohen** [comment]
Thanks. I'll look into that.

**Comment by SrgntBallistic** [comment]
In the meantime you might want to check out the Webcam Sidebar plugin which will always display the plugin in the sidebar. Would probably have the same end result you're looking for

**Comment by SargonofAssyria** [comment]
The problem with the Webcam Sidebar plugin is that I do not have enough room for all on the sidebar.

**Comment by TalZiv** [comment]
first of all beautiful plugin.
Second, this is exactly what I wanted to post :)
Manged to this using Chrome dev mode, but would love to see it integrated with a smaller video window:
![image](https://user-images.githubusercontent.com/22313897/64911726-17d7d900-d72e-11e9-9ba8-f12fd0bea1c7.png)

**Comment by aherzberg** [comment]
I would also like to see this feature added. Would you be open to a pull request if I made the addition? Great job btw. Awesome Plugin.

**Comment by StefanCohen** [comment]
I didn’t have time for this yesterday in 1.1.0 so I would appreciate a PR. I think this should have a new setting in the plugin settings (“Enable Camera”, disabled by default).

**Comment by StefanCohen** [comment]
Basic support for a webcam has been added in nextrelease:

<img width="970" alt="Screenshot 2019-09-17 at 13 39 09" src="https://user-images.githubusercontent.com/33824565/65038635-ae83e000-d950-11e9-9941-06f2840c860b.png">

**Comment by StefanCohen** [comment]
Fixed in 1.2.0

**Comment by solyxius** [comment]
Great work Stefan, love the plugin!

With the new webcam view, would it be possible to a) "_shrink to fit_" (to eliminate the scroll bars), and b) enable a click to enter full screen view, another click to return to dashboard view (like the Sidebar Webcam plugin behaviour)?

![2019-09-19_10-20-23](https://user-images.githubusercontent.com/38299827/65198638-312eab80-dac7-11e9-8353-194278fcf875.png)
