### ISSUE TITLE
Feature Request: Raspberry Pi Performance Specs

### ISSUE THREAD

**Issue by SrgntBallistic** [StefanCohen/OctoPrint-Dashboard#20]
I've been pretty surprised to see that there's no active plugins to view a Raspberry Pi (or other machine) system performance specs. Like CPU Temp/Speed/Utilization, Ram Utilization, Storage, Etc...

This would be particularly useful for Pi's. I've been using Octolapse and playing around with using a Wyze Cam as a camera source. This along with the other many plugins has me concerned with the Pi throttling and impacting prints.

I started designing/wireframing a possible tab to show these specs and... Voila your plugin popped up. Seems like it might be more worthwhile to try and add this to your plugin than make it a standalone plugin.

There's an older plugin that doesn't seem to work anymore. I was going to use this as a starting point:
https://github.com/myersCody/OctoPrint-Cpustatus

Looks like they were basically writing the results of psutil to a text file and reading that into the UI.

`cpuUsage = psutil.cpu_percent(interval=1)
testFile = open("test.txt", "w")
testFile.write(cpuUsage)
testFile.close()`

I believe the author of that plugin pull some code from NavBarTemp. Looking at that he has a class for getting the system temp for different types of systems including Raspberry Pi's.

https://github.com/imrahil/OctoPrint-NavbarTemp/blob/master/octoprint_navbartemp/libs/sbc.py

**Comment by StefanCohen** [comment]
That sounds interesting and would be a nice fit I think. Would you like to collaborate on that?

**Comment by SrgntBallistic** [comment]
> That sounds interesting and would be a nice fit I think. Would you like to collaborate on that?

Quite possibly. I've never worked on an OctoPrint Plugin or contributed to a github for that matter. But I think I have the capacity to do so.

What would you recommend to do to start?

**Comment by StefanCohen** [comment]
> Quite possibly. I've never worked on an OctoPrint Plugin or contributed to a github for that matter. 
That makes two of us :)

I looked at psutil. It should be possible to include it in the plugin and have it installed at the same time using the plugin manager. I don't see why it would be necesary to write it to file unless you want time graphs.

What metrics would you like to include? Given the grid-based layout of the dasboard, I'm thinking multiples of three. Something like: CPU usage, Mem usage, Disk Usage. 
After that: CPU Temp, Load, ???

Can you upload a wireframe of what you had in mind?

**Comment by StefanCohen** [comment]
Getting the CPU, MEM and HD/SD info via psutil was easy:
<img width="648" alt="Screenshot 2019-09-16 at 15 30 50" src="https://user-images.githubusercontent.com/33824565/64962114-255ca280-d897-11e9-9c21-b5041f8bf806.png">

Is this similar to what you had in mind?

**Comment by SrgntBallistic** [comment]
That's a pretty good turn around! Hahah. That's pretty much exactly what I had imaged and started writing up. I had names written out instead of icons but those seem perfect. Temp is really the only thing I can think of that would be useful at the moment. I'm sure the community might be able to suggest some others to keep the 3 column grid going.

You Rock!

**Comment by StefanCohen** [comment]
I added the CPU temp. That may unfortunately not work on anything other than an RPi as the sensor ID is hardcoded for now. I'll see if I can address that before the next release.
<img width="559" alt="Screenshot 2019-09-16 at 21 51 49" src="https://user-images.githubusercontent.com/33824565/64989120-24466800-d8cd-11e9-9b7b-21ccb453f7f8.png">

**Comment by StefanCohen** [comment]
Fixed in 1.2.0

**Comment by vbz89** [comment]
Does this work for any RPi? I have a RPi 3B and I get "0" Values for all 3 parameters.

![image](https://user-images.githubusercontent.com/29619546/65777836-5fb12400-e162-11e9-97dc-013881eb97a4.png)

**Comment by StefanCohen** [comment]
It *should* work on any RPi and it does work on my 3b and 3b+. Are you on OctopPi? What version in that case?

it looks like psutil doesn't return anything.

What happens if you try the following from a terminal:
`source ~/oprint/bin/activate`
`python`
`>>>import psutil`
`>>>psutil.virtual_memory().percent`

**Comment by vbz89** [comment]
Sorry for the late reply, I am using octopi 0.14.0, octoprint 1.3.11

The above commands gave me "32.2"

**Comment by StefanCohen** [comment]
Ok. That means that psUtil is at least available. I wonder if there may be a difference between OctoPi 1.14 and 1.16 that I use? Do you have the possibility to try a later version?

**Comment by vbz89** [comment]
I will take a backup image of my sd card and try a fresh installation tomorrow and get back to you on the results on 0.16. I appreciate the quick response. Thanks.

**Comment by vbz89** [comment]
I tried today on a clean install of 0.16, it is working correctly. So I guess it's a problem with 0.14. Time to shift all my stuff to a new installation I guess.

**Comment by StefanCohen** [comment]
Ok. Good to know. I will set a minimum version in the installer

**Comment by o5** [comment]
I've installed this plugin and enabled "Show RPi System Info" and it does not work :/ 

<img width="661" alt="Screenshot 2020-09-20 at 20 27 57" src="https://user-images.githubusercontent.com/218562/93718964-d7503e00-fb7f-11ea-98ab-5759449f83ce.png">

```
Dashboard 1.14.0
OctoPrint 1.4.2
Python 3.7.3
Raspbian 5.4.51-v7l+ #1333
Raspberry Pi 4 Model B Rev 1.1
```

I tried to install psutil using pip and it looks work
```bash
pi@raspberrypi:~ $ python3
Python 3.7.3 (default, Jul 25 2020, 13:03:44)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import psutil
>>> psutil.virtual_memory().percent
14.7
>>>
```
