### ISSUE TITLE
Temperature Gauge Maximums settings do not work for Bed Max

### ISSUE THREAD

**Issue by THHL** [StefanCohen/OctoPrint-Dashboard#23]
The Temperature Gauge Maximums settings for Bed Max has no effect.
(The same setting for Hotend Max works as expected.)

1. Go to Dashboard Plugin Settings in OctoPrint
2. Click on Bed Max button down
3. Save settings
4. In Dashboard, see that the Gauge did not change

**Expected behavior**
The Gauge should have changed according to the new Bed Max setting

**Screenshots**

![Auswahl_007](https://user-images.githubusercontent.com/48371295/65081692-7ad2a580-d9a4-11e9-8c77-6f68145502fb.png)

![Auswahl_006](https://user-images.githubusercontent.com/48371295/65081701-84f4a400-d9a4-11e9-94b3-1b15a17e1e86.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 17.04
 - Browser: Firefox
 - Version: 69.0

**Comment by StefanCohen** [comment]
Reproduced. Will fix

**Comment by StefanCohen** [comment]
The template from the original PR got overwritten at some point so the changes got lost after testing. I have added the correct version to the next release.

**Comment by StefanCohen** [comment]
Fixed in 1.2.0
