### ISSUE TITLE
Progress reported is incorrect

### ISSUE THREAD

**Issue by jimmyeao** [StefanCohen/OctoPrint-Dashboard#25]
**Describe the bug**
The dashboard (and now OCtoprint) is reporting incorrect progress that conflicts with the LCD progress and real progress

**To Reproduce**
Start any print

**Expected behaviour**
Progress should be correct - see attached, reports over 40% complete on 2nd layer. Printer reports 14%

**Screenshots**
![progerr](https://user-images.githubusercontent.com/5197831/65131417-1856c500-d9f7-11e9-835b-dba7370e3e0f.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win 10
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22]  76.0.3809.132

**Additional context**

**Comment by jimmyeao** [comment]
Its the same, so perhaps something weird going on with Octoprint?

**Comment by StefanCohen** [comment]
Yes. This is likelly something with OctoPrint so I'll close this issue. You can also try installing OctoPrint-PrintTimeGenius to see if that helps.
