### ISSUE TITLE
Autohide Hotend display if not used

### ISSUE THREAD

**Issue by LMS0815** [StefanCohen/OctoPrint-Dashboard#26]
My printer has 2 hotends, but only 1 is used at a time. 
To save some space I would like to (auto)hide the display of a hotend, if the target temperature is = 0 (zero). 
This would free space for the Fan Gauge (which I had to hide because of limited space.
![Anmerkung 2019-09-18 160441](https://user-images.githubusercontent.com/8235214/65155728-11977480-da2e-11e9-887f-f26076c4659c.png)

**Comment by StefanCohen** [comment]
I think we can try this as an "advanced" setting.

**Comment by StefanCohen** [comment]
Allright. I have tried this but I'm not sure that this is good enough. The new setting "Hide hotend(s) when target temp = 0" will hide _all_ hotends until at least one is heated up. This will in your case mean that only the bed and fan is visible when the printer is idle. Is that what you was looking for?

**Comment by StefanCohen** [comment]
Fixed in 1.3.0

**Comment by LMS0815** [comment]
Yes. Perfect. If thee is no Temperatur set there is no need to monitor. I have to check it,but I am very sure I'll Ike it. THANK YOU!

**Comment by StefanCohen** [comment]
The feature was causing problems for others so I had to revert it and push 1.3.1 without it. I will have to give it a go some other day.

**Comment by StefanCohen** [comment]
Allright. I think I have fixed it now. I will release it this weekend.
