### ISSUE TITLE
Flip camera

### ISSUE THREAD

**Issue by DerKleene** [StefanCohen/OctoPrint-Dashboard#28]
Hello,

my camera is flipped in Octoprint under the options.
It would be nice if this would be in the dashboard too.
Sorry for my bad English, but I'm from Germany.

Greetings Heiko
![cam1](https://user-images.githubusercontent.com/19396070/65186312-aff4fb80-da69-11e9-8327-4b8f383ac359.png)
![cam2](https://user-images.githubusercontent.com/19396070/65186315-b1bebf00-da69-11e9-9b46-ec2386bc8bae.png)

**Comment by StefanCohen** [comment]
Thanks. I’m working on it.

**Comment by DerKleene** [comment]
Hi,
Nice to hear, that makes it a lot easier to look at.
Need to mention that one of the best plugins is what I saw.
Best regards
Heiko

**Comment by StefanCohen** [comment]
Fixed in 1.3.0
