### ISSUE TITLE
Scale Webcam

### ISSUE THREAD

**Issue by reyd8** [StefanCohen/OctoPrint-Dashboard#29]
Webcam is zoomed in quite a bit, more useful to just turn it off at this point
![dashcam](https://user-images.githubusercontent.com/48224621/65203851-f3dc0680-da51-11e9-8a21-5e88d9029ccc.jpg)

**Comment by StefanCohen** [comment]
Thanks. I’m working on a fix.

**Comment by StefanCohen** [comment]
Fixed in 1.3.0
