### ISSUE TITLE
Feature Request: Orange PI Performance Specs

### ISSUE THREAD

**Issue by alakond** [StefanCohen/OctoPrint-Dashboard#30]
You have released a plug-in for Rasbery PI, is it possible to add support for Orange PI? Thnx!
![dashboard](https://user-images.githubusercontent.com/3037265/65223471-b2436e00-dada-11e9-960b-50be716e3d45.png)

**Comment by StefanCohen** [comment]
Thanks for the feedback.
I don't have access to an Orange PI, so it will not be possible for me to support it. But feel free to submit a pull request and I will take a look at it.
The Fan, layer, height and avg layer time issue is related to the warning message at the bottom of the Dasboard in your screenshot.

**Comment by alakond** [comment]
Thanks for the answer.
I can give remote access to my orange pi SSH and the web to my octoprint.

**Comment by StefanCohen** [comment]
Thanks, but that is not a long-term solution for me.
