### ISSUE TITLE
broken links behind reverse proxy

### ISSUE THREAD

**Issue by tombic** [StefanCohen/OctoPrint-Dashboard#34]
Please make links to icons relative for octopi installations behind simple reverse proxy. 
When octopi is behind reverse proxy and in subdirectory it can't find links to icons, because address is starting with /. If it is possible can you make links relative to page (with no / at the beginning of address?) For example "/plugin/dashboard/static/img/hotend-icon.png" -> "plugin/dashboard/static/img/hotend-icon.png".
BTW, very nice plugin. It is helpful to view all the status info on one place.

**Comment by StefanCohen** [comment]
It seems like the slash in the beginning has to be there in order to work on a non-proxied installation. Have you tried removing it locally to verify that it still works in both scenarios?

**Comment by tombic** [comment]
When checked locally (changed that in firefox inspection window) it works without slash in both proxied and non proxied scenario. But I can't say that it may not create any problem somewhere else as I am not web developer.

**Comment by StefanCohen** [comment]
> I am not web developer.

Me neither. I’m just pretending :)  Ok. I will have to test all the install methods to make sure it doesn’t breaks something.

**Comment by tombic** [comment]
1.4.0 works for me locally and over internet and proxy too. Good.
You pretend very well :-))) Thanks.
