### ISSUE TITLE
lost hot end temp gauge

### ISSUE THREAD

**Issue by simmll1** [StefanCohen/OctoPrint-Dashboard#35]
The other day you released your update to 1.3.0.  I installed it with no issues.  Then 2 days later i got a message in octoprint that a new release was available for your plugin.  I thought it was odd that it stated it was the same release 1.3.0.  I went ahead and installed it.  Now I dont see the temp of the hot end during a print

**Comment by StefanCohen** [comment]
Hi. 1.2.0 was released three days ago. I released 1.3.0 yesterday. It included a new feature that was flawed (Issue #33). It caused the problem you have encountered. I reverted the feature in 1.3.1 that was released a few hours later. You can see the full release history here:   https://github.com/StefanCohen/OctoPrint-Dashboard/releases

I recommend that you upgrade to 1.3.1.
