### ISSUE TITLE
Full screen mode

### ISSUE THREAD

**Issue by Ha-Z-Z-ard** [StefanCohen/OctoPrint-Dashboard#38]
**Is your feature request related to a problem? Please describe.**
no problem,is it possable to have the dashboard within its own frame,so this could be made fullscreen?

**Describe the solution you'd like**
fullscreen dashboard for a " info screen full display" with setups that have screens for there printers

**Describe alternatives you've considered**
just learning code and alterntives are beyond my current expertise

**Comment by StefanCohen** [comment]
Ok. I have added a setting for enabling fullscreen mode (experimental for now) in the next release. I haven't made any attempt to style it differently if in fullscreen yet. I think the layout should be adjusted significantly when in fullscreen, but my css-fu is very limited, so let's see if you or anybody else would like to contribute some styling.

**Comment by Ha-Z-Z-ard** [comment]
Amazing Stefan, thank you

I have limited knowledge with css styling but wouldn't mind learning so
will have a wee prod about



Scott Reid

**Comment by chadlichty** [comment]
This is great.  One issue I saw was the webCam was cropped in full-screen mode.  That issue is fixed in the regular display.  Looks great though.

**Comment by StefanCohen** [comment]
I know. The webcam issue is however technically different than the one in 1.2.0 and can be solved by restyling the view in fullscreen.  
The fullscreen mode could benefit from a different layout where the cam and dash resides side by side horizontally or maybe overlaid on eachother.

**Comment by Ha-Z-Z-ard** [comment]
This is amazing..... How easy would it be to move the gcode viewer side by
side with webcam in y. the full screen mode?

I think it. Would be amazing to have all the stats at the top,webcam and.
Gcode viewer Centre then progress at time finish at bottom.

Scott Reid

**Comment by StefanCohen** [comment]
It is certainly possible to combine the views.Consolidate Temp Control does something similar: https://github.com/jneilliii/OctoPrint-ConsolidateTempControl

But I'm not sure I want to go that route. I think Less is more and I would rather do something like FullScreen WebCam does and as you mentioned show the webcam view fullscreen and overlay a bar or two with the gauges insted: https://plugins.octoprint.org/plugins/fullscreen/ I think I'll mock it up this weekend to see what makes sense.

**Comment by Ha-Z-Z-ard** [comment]
Sounds great, I think your work is great so whatever you want to do is great

Scott Reid

**Comment by StefanCohen** [comment]
Maybe something like this:

<img width="954" alt="Screenshot 2019-09-21 at 21 21 40" src="https://user-images.githubusercontent.com/33824565/65378301-b6c47e00-dcb6-11e9-826d-94aa0b0fc423.png">

**Comment by Ha-Z-Z-ard** [comment]
Dude, that looks amazing.

Scott Reid

**Comment by xeddog** [comment]
Just a suggestion, but I would much rather see full screen WITHIN THE BROWSER Window.  That would allow me to scale browser windows and see two or more different instances on a single screen.

**Comment by chadlichty** [comment]
Looks great!

**Comment by StefanCohen** [comment]
@xeddog I think I like that better than the current fullscreen. It is a bit like Octoprint TouchUI works. 

Maybe something like this?

<img width="955" alt="Screenshot 2019-09-22 at 08 38 42" src="https://user-images.githubusercontent.com/33824565/65383353-c70b4600-dd14-11e9-83a6-f828374c5394.png">

**Comment by j7126** [comment]
That looks pretty good. I would be happy to give any help if you need.

**Comment by StefanCohen** [comment]
@j7126 I would appreciate any help I can get with this. CSS is pretty much black magic to me. 

The Idea I have is to go with the layout above (dashboard left, webcam right) when In fullscreen. That would (hopefully) not need a separate jinja template. I would like to keep the rest of the styling   and compatibility with Themeify but I like your approach of placing the icons above the texts as you did with the TouchUI PR.  

Maybe something like this, but I'm open for better alternatives: 
![Screenshot 2019-09-22 at 10 52 05](https://user-images.githubusercontent.com/33824565/65384885-dba50980-dd27-11e9-8b3e-8d260eb4962f.png)

The question is what to do if there is no Webcam or if it is disabled. One approach could be to just center the dashboard and spread it out a bit horisontally. Do you have any suggestions?

I would really appreciate if you would like to collaborate on this.

**Comment by j7126** [comment]
I will try to do something like that, the only thing is I do not have a webcam to test with but I will try to work around that.

**Comment by StefanCohen** [comment]
Cool. I guess you can link to any publicly available webcam feed from a site such as opentopia or maybe just a static image. I just tried and here's one that works: http://92.60.192.245/cgi-bin/faststream.jpg?stream=full&fps=0

**Comment by jimmyeao** [comment]
> @xeddog I think I like that better than the current fullscreen. It is a bit like Octoprint TouchUI works.
> 
> Maybe something like this?
> 
> <img alt="Screenshot 2019-09-22 at 08 38 42" width="955" src="https://user-images.githubusercontent.com/33824565/65383353-c70b4600-dd14-11e9-83a6-f828374c5394.png">

That looks awesome!
