### ISSUE TITLE
Hi res webcam image doesnt scale well

### ISSUE THREAD

**Issue by jimmyeao** [StefanCohen/OctoPrint-Dashboard#41]
**Describe the bug**
Camera has bottom half cut off in full screen mode

**To Reproduce**
Configure camera for 1280x720, enter full screen mode, only top half of image is shown

**Expected behavior**
Image would be scaled to fit

**Screenshots**
![dashboard](https://user-images.githubusercontent.com/5197831/65386248-f16afc80-dd30-11e9-9a20-1c7c064082ed.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win 10
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] Current Version

**Additional context**
Love the full screen view. Would be good to have a 'panic' button to cancel the print. Maybe one we can add some custom gcode to so we can say, stop print and move up 5 mm

**Comment by StefanCohen** [comment]
Thanks. I'm aware. That's why the fullscreen option is marked "experimental". The fullscreen CSS will be redesigned.

**Comment by j7126** [comment]
Fixed

**Comment by StefanCohen** [comment]
Fixed in 1.5.0
