### ISSUE TITLE
Ability to rotate webcam feed

### ISSUE THREAD

**Issue by ruralaccent** [StefanCohen/OctoPrint-Dashboard#42]
Issue
When the webcam feed is shown, it only displays it in standard orientation. Some uses have to mount webcams in different orientations, so benefit from controls to rotate the webcam feed.

Resolution
Introduce controls to rotate the webcam feed e.g. 90 clockwise, 90 anti-clockwise, 180 etc.

Alternatives
Physically mount camera differently - but not always possible or desirable.

Thank you for a great plugin! :)

**Comment by StefanCohen** [comment]
Flipping verically and horisontally is supported and should work. I have tried to support the rotation configured in octoprint too but but not yet succeeded.

**Comment by StefanCohen** [comment]
Fixed in 1.5.0
