### ISSUE TITLE
Fan speed off even is on

### ISSUE THREAD

**Issue by ochm** [StefanCohen/OctoPrint-Dashboard#49]
When print starts while user is logged in, fan speed is displayed OK.
But if you do logout and back login (print is still running), the fan speed indicator remains Off.
The state of fan indicator is changed after some time (i don't know when), but changed...

Tried in FF, Chrome, Safari.
Running latest Dashboard (1.5.0)

**Comment by StefanCohen** [comment]
I haven't been able to reproduce this. The Fan, layer, height and average layer time data is coming from the DisplayLayerProgress plugin via an event hook and the Dashboard is updated on the next layer change when the next event is fired (as expected).

**Comment by ochm** [comment]
OK, if the dashboard is updated on the layer change, i must wait. Thank you
