### ISSUE TITLE
1.6.0 breaks M117 command!

### ISSUE THREAD

**Issue by ochm** [StefanCohen/OctoPrint-Dashboard#53]
When updated Dashboard to version 1.6.0, printer stopped display about Octopi Connected,disconnected. 
After short investigation i foud that M117 is not sent, is not visible in serial monitor log.
Ony some like M117 x123 is vissible, but no M117 Hello world

**To Reproduce**
Try to send M117 Something and do verify what is displayed on printer.

**Expected behavior**
Display on printer what was sent by M117.

When the dashboard plugin is disabled od uninstalled, everything about M117 goes well.

**Comment by StefanCohen** [comment]
Thanks. I think I know what went wrong and will try to fix that.

**Comment by StefanCohen** [comment]
Confirmed. It was a botched GCODE parser introduced in v1.6.0. Fixed in v1.6.0.
