### ISSUE TITLE
1.6.0 can't send klipper Extended G-Code Commands

### ISSUE THREAD

**Issue by escapac** [StefanCohen/OctoPrint-Dashboard#54]
I updated to 1.6.0 and now I can't send any klipper extended G-code commands to my printer.
Before update to 1.6 klipper extended G-code commands worked. I disabled dashboard plugin only and problem disappears.

**To Reproduce**
1. Go to terminal or any other place where you can send g-codes to printer.
2. Send example restart command to printer or any other klipper extended G-code commands.

**Expected behavior**
With restart command klipper should restart.

 - OS: WIN 10
 - Browser Vivaldi
 - Version 2.7.1628.33 (Stable channel) (32-bit)

**Comment by StefanCohen** [comment]
Thanks. This is probably the same as #53 but I will take a look just in case it something else causing this.

**Comment by StefanCohen** [comment]
Confirmed. It was a botched GCODE parser introduced in v1.6.0. Fixed in v1.6.1.

**Comment by StefanCohen** [comment]
I have now passed a full print on my Klipper printer.
