### ISSUE TITLE
raspberry temperature sensor (dht11)

### ISSUE THREAD

**Issue by iapetus696** [StefanCohen/OctoPrint-Dashboard#57]
Edit by StefanCohen: I have a temperature sensor (dht11) on my octoprint i wish i can see the temp & humidity in the dashboard like the CPU temperature

**Comment by StefanCohen** [comment]
Hi. The details of your request seems to have been lost.

**Comment by iapetus696** [comment]
sorry ..... i have a temperature sensor (dht11) on my octoprint i wish i can see the temp in the dashboard like the CPU  temperature

**Comment by iapetus696** [comment]
Now im using the enclosure plugin

**Comment by StefanCohen** [comment]
Ok. I understand now. I agree that it would be a nice addition to the dashboard but I don't have that kind of sensor at hand so I don't feel comfortable supporting it when users asks questions about it.

**Comment by iapetus696** [comment]
maybe a way to pull output values from other plugin like  enclosure plugin

**Comment by StefanCohen** [comment]
Yes. I will take a look at that possibility.

**Comment by StefanCohen** [comment]
I will reach out to the plugin developer and see if he is willing to add an event hook to get the temps.

**Comment by iapetus696** [comment]
Thank you... i hope the best

**Comment by StefanCohen** [comment]
No problem. My FR is available here: https://github.com/vitormhenrique/OctoPrint-Enclosure/issues/260

**Comment by StefanCohen** [comment]
I went out and bought a dht11 today. It seems to work with the Enclosure plugin:

![Screenshot 2019-10-02 at 16 45 27](https://user-images.githubusercontent.com/33824565/66054400-33b3eb00-e534-11e9-80c3-09eb3ee9af16.png)

**Comment by iapetus696** [comment]
yes work fine and with many sensors but i prefer all in the Dashboard

**Comment by iapetus696** [comment]
all the values *

**Comment by iapetus696** [comment]
Enclosure plugin is very good

**Comment by StefanCohen** [comment]
I haven't received any feedback on the Enclosure plugin FR so I decided to give it a go myself this afternoon:

![Screenshot 2019-10-06 at 16 17 49](https://user-images.githubusercontent.com/33824565/66270526-2315b480-e855-11e9-8703-5f8a8979265a.png)

Is one sensor good enough for now?

**Comment by iapetus696** [comment]
Thank you, one is good enough for me .... I think 2 is good idea .one for the  enclosure one for the fillament or the room temp .

**Comment by StefanCohen** [comment]
The dash is getting crowded with data so one will have to do for now. This will be available in v1.10.0
