### ISSUE TITLE
Progress "Bar" Guage Obscures Percent Value

### ISSUE THREAD

**Issue by doughoyt** [StefanCohen/OctoPrint-Dashboard#6]
When using "bar" progress gauge type, the bar obscures the actual percentage when you get to the ~ 50% mark.

1. Ensure progress gauge type is bar in plugin settings
2. Start print and observer that actual percentage displays
3. Wait until 50% or so and observer that percentage is obscured by bar
![Dashboard2](https://user-images.githubusercontent.com/11353975/64725972-e7284300-d492-11e9-91dc-17ab717948d8.PNG)

I would expect the percentage value to be "on top" of the progress bar and readable as the background changes during the bar's progress.

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser Firefox 
 - Version 69

Moving the class="progress-text-back" span _below_ the class="bar" div appears to fix the issue.  This is around line 101 of dashboard_tab.jinja2

![Dashboard1](https://user-images.githubusercontent.com/11353975/64725948-d972bd80-d492-11e9-9624-8330af92866c.PNG)

**Comment by StefanCohen** [comment]
Thanks. I didn't notice that myself. I'll try to reproduce it.

**Comment by StefanCohen** [comment]
Fixed in 1.1.0
