### ISSUE TITLE
Full screen mode is bigger than screen

### ISSUE THREAD

**Issue by ochm** [StefanCohen/OctoPrint-Dashboard#71]
**Describe the bug**
In full screen of dashboard i see on my both monitors the most low informations out of screen. Both are digitaly connected, there is no issue with screen size settingand i see no issues in other applications or windows main bar. 

**To Reproduce**
Start fullscreen display

**Expected behavior**
Is it possible to move whole content of fullscreen approx. 0.5cm higher?

**Screenshots**
![screenshot-bottom](https://user-images.githubusercontent.com/47606742/66245382-c52a8500-e70d-11e9-82de-b2c6683d7e1d.PNG)
![screenshot-top](https://user-images.githubusercontent.com/47606742/66245387-c9ef3900-e70d-11e9-97d0-c2fd095e6267.PNG)
![screenshot-with-windows-panel](https://user-images.githubusercontent.com/47606742/66245444-1f2b4a80-e70e-11e9-80ec-b92f6ff4e920.PNG)

**Desktop (please complete the following information):**
W8.1
resolution 1920x1080

Thank you.

**Comment by StefanCohen** [comment]
I have a similar problem in Safari. What browser are you using?

Tagging @j7126

**Comment by ochm** [comment]
Currently I'm using Chrome, in the FF ESR is the same problem.

**Comment by j7126** [comment]
I'll look into it.

**Comment by LMS0815** [comment]
Same issue with Chrome on 1280x1024 Monitor

**Comment by elvinhaak** [comment]
Kind of the Same 'issue'. Using  the Pi's display, using epiphany-browser.
The icons about the info are coming on screen but not any info. I'll try to make a screenshot using VNC. Actually, it is divided over multiple pages, but none with info although scrolling through them.

**Comment by StefanCohen** [comment]
@elvinhaak That looks like a completely different Issue. Do you mind removing this and opening up a new one to keep this thread on topic?

**Comment by elvinhaak** [comment]
ok I will

Op zo 6 okt. 2019 om 14:40 schreef StefanCohen <notifications@github.com>:

**Comment by StefanCohen** [comment]
WIll be fixed in 1.11.0 I have reduced the bottom padding for the grid containers to free up some space. For fitting the dashboard on smaller screens, either reduce the number of widgets or use the bar progress type to save some vertical space.

**Comment by StefanCohen** [comment]
Fixed in 1.11.0
