### ISSUE TITLE
Dashboard height indicator incorrect

### ISSUE THREAD

**Issue by RyanParle** [StefanCohen/OctoPrint-Dashboard#76]
**Describe the bug**

Current height and total height values reported incorrectly in dashboard plugin. As an example during a recent print I found that the values reported by the DisplayZ and DisplayLayerProgress plugins were reporting the current height as 123.79mm and a total height of 155.85 however the dashboard plugin is showing a current height of 124.69 and a total height of 154.85

**To Reproduce**

simply compare values between dashboard and DisplayLayerProgress

**Expected behavior**

The values to match

**Screenshots**

![dashboard layer height](https://user-images.githubusercontent.com/3680655/66270384-c8775b00-e84a-11e9-819d-2313a49318da.JPG)

**Desktop (please complete the following information):**

Issue independent of OS / Browser

**Comment by StefanCohen** [comment]
Thanks. Can you tell me what setting you have in the following dialog in the DisplayLayerProgress plugin settings:

![Screenshot 2019-10-06 at 20 36 06](https://user-images.githubusercontent.com/33824565/66273943-6aae3780-e879-11e9-9ee6-1023f3a03042.png)

**Comment by StefanCohen** [comment]
Can you please also attach a gcode file that has this problem?

**Comment by StefanCohen** [comment]
I can see this problem too with the latest DisplayLayerProgress release. This may be a problem with the data sent from DisplayLayerProgress thru the event handler. This is probably related to #81

**Comment by StefanCohen** [comment]
Fixed in v1.10.2

**Comment by RyanParle** [comment]
Hi Stefan, Thanks for the quick work on getting an update out, sorry i was not able to send you more information, I've been a little busy over the last few days.
