### ISSUE TITLE
Layer progress gauge.

### ISSUE THREAD

**Issue by StefanCohen** [StefanCohen/OctoPrint-Dashboard#8]
**Is your feature request related to a problem? Please describe.**
The progress gauge only displays the total print progress.

**Describe the solution you'd like**
Add a gauge or enhance the existing progress gauge to display the progress of the current layer.

**Describe alternatives you've considered**
N/A

**Additional context**
The per layer progress should be possible to get from the Gcode Viewer tab.

**Comment by j7126** [comment]
@StefanCohen are you currently working on this?

**Comment by j7126** [comment]
I have just been looking at this briefly and I think i have a way to get the percentage of the current layer from the gcode viewer tab

    $('#gcode_command_slider>.slider-track>.slider-selection').width() / $('#gcode_command_slider>.slider-track>.slider-selection').parent().width() * 100

**Comment by j7126** [comment]
I have found a way to do it which gets it from the `gcodeViewModel._renderPercentage` function.
Will make a pull request at some point.

**Comment by j7126** [comment]
I have found a way of getting the percentage from the Gcode View Model.

Will make a pull request when it is done.

**Comment by StefanCohen** [comment]
Nice. Have you managed to get it when the gcode tab is out of focus?

**Comment by j7126** [comment]
yes

**Comment by StefanCohen** [comment]
Cool. 

I was thinking that It would be nice to display the layer progress using the same type of gauge as the total layer (circle or bar). In that case I think the Layer progress gauge type has to be independently selectable.

![Screenshot 2019-10-01 at 08 20 55](https://user-images.githubusercontent.com/33824565/65938838-6c649f00-e424-11e9-867c-8cc479b8b7ad.png)
 
What do you think?

**Comment by j7126** [comment]
Looks good, I will try to do that

**Comment by j7126** [comment]
This might take a while, I am encountering a lot of problems.

**Comment by j7126** [comment]
I will make a Pull request soon adding this as an experimental feature.

**Comment by j7126** [comment]
It still has some bugs but it is pretty good at this point. Marked it as an experimental feature in the settings page. 

PR #72

**Comment by StefanCohen** [comment]
That PR It is absolutely fantastic. Thanks!

I haven't found any bugs yet but I'll run some more tests tomorrow to see if can find something.
