### ISSUE TITLE
Dashboard loads webcam stream upon loading and never unloads it

### ISSUE THREAD

**Issue by EpicLPer** [StefanCohen/OctoPrint-Dashboard#80]
**Describe the bug**
I was wondering why my PC constantly downloaded ~3MB/s so I checked the Ressource Manager and found the OctoPi tab as the issue. Once I disabled the Dashboard Plugin the issue instantly went away.

**To Reproduce**
1. As soon as Dashboard is installed it'll load the webcam stream
2. If this doesn't work enable, save, then disable the "Show Webcam" in the settings. Bug will now occur.

**Expected behavior**
Webcam Stream shouldn't be loaded upon finishing loading the page or should be unloaded if tab isn't active for a few seconds like the normal Control page does it.

**Screenshots**
![image](https://user-images.githubusercontent.com/8442196/66327616-66daed80-e92b-11e9-9c6d-53b6708810d0.png)

**Desktop (please complete the following information):**
 - Device: Desktop PC
 - OS: Windows 10 1903
 - Browser: Chrome, 77.0.3865.90
 - Version: 1.10.1

**Comment by StefanCohen** [comment]
That is correct. I have not implemented this yet.

**Comment by StefanCohen** [comment]
Partly fixed in 1.11.0

The webcam stream is not loaded if "Show Webcam" is disabled. I will not implement the loading/unloading of the stream on tab change as I couldn't get that to work reliably.

**Comment by StefanCohen** [comment]
Fixed in 1.11.0
