### ISSUE TITLE
Bug on RPI clones

### ISSUE THREAD

**Issue by mamaich** [StefanCohen/OctoPrint-Dashboard#88]
File __init__.py. Old code:
```
 try: #Check to see if we are on an RPI or not
   import RPi.GPIO as gpio
   on_rpi = True
 except (ImportError, RuntimeError):
   on_rpi = False
 
 if on_rpi == True:
     import Adafruit_DHT
```

If the RPI or clone does not have Adafruit_DHT module - the plugin would crash. 
The fix is simple - move import inside try block:
```
 try: #Check to see if we are on an RPI or not
   import RPi.GPIO as gpio
   import Adafruit_DHT
   on_rpi = True
 except (ImportError, RuntimeError):
   on_rpi = False

```
This would fix Dashboard on Orange PI

**Comment by StefanCohen** [comment]
Thanks,

I want to understand this. The Clone can import RPi.GPIO but not Adafruit_DHT? Is that correct?

**Comment by StefanCohen** [comment]
I have decided to remove the dependency to the DHT module and rely on the Enclosure plugin instead for the next version so this will become a moot point. That’s why I will close this report.
