### ISSUE TITLE
Remove Context menus

### ISSUE THREAD

**Issue by StefanCohen** [StefanCohen/OctoPrint-Dashboard#93]
**Is your feature request related to a problem? Please describe.**
The context menus are too obscure to be useful. User don't know that they are there and they are worthless on touch devices.

**Describe the solution you'd like**
Simply remove them.

**Comment by j7126** [comment]
I think it would be better to leave them in but have a setting to enable them which is disabled by default. Some people might still use them.

**Comment by StefanCohen** [comment]
I have considered that but opted to actually remove them while it is still early and not too many users are affected. I added them with the intention to implement controls for temperatures and maybe also motion control but I have changed my mind and will not go that way with the dashboard. My full reasoning is explained in #70.

**Comment by StefanCohen** [comment]
Fixed in 1.11.0
